site_name: Scraping class
theme: readthedocs
repo_url: https://github.com/ireapps/scraping-class/
markdown_extensions: [admonition,tables,toc,headerid]
pages:
- ["index.md", "Table of contents", "Home"]